### ISSUE TITLE
Issues about squad_crawler.py

### ISSUE THREAD

**Issue by ArchieGu** [mrthlinh/FIFA-World-Cup-Prediction#3]
When I ran `python3 squad_crawler.py,` I got this error:
`France - Didier Deschamps
Traceback (most recent call last):
  File "squad_crawler.py", line 64, in <module>
    player_name = row.select("th > a")[0].get_text()
IndexError: list index out of range`

Would you please tell me how to fix this??

Thx.

**Comment by ArchieGu** [comment]
Oh, just modify the code into `name = row.findAll('th')  player_name = name[0].get_text()` can solve the problem.

Is that a right solution?

**Comment by mrthlinh** [comment]
@ArchieGu Because the HTML layout of web pages of squad (from Wikipedia) are not always consistent so if you run on a new page, there is maybe some problems. Which URL you are running?

**Comment by ArchieGu** [comment]
@mrthlinh 
I am using this one https://en.wikipedia.org/wiki/UEFA_Euro_2016_squads
I check the source code of the website, and find out the 'th' tag can be used to crawl player's name, don't know is that a good solution. LOL.

BTW, what dose the code `tables[i].select("th > a")` mean? I am confused with the `("th > a")`.
And for squad_strength, why use two different crawlers?  
Thanks.

**Comment by mrthlinh** [comment]
@ArchieGu `tables[i].select("th > a")` select all <a> elements where the parent is a <th> element
More references:
https://www.w3schools.com/cssref/css_selectors.asp

**Comment by mrthlinh** [comment]
@ArchieGu two different crawlers are for two websites, one if https://www.fifaindex.com/ and other is https://sofifa.com/

**Comment by ArchieGu** [comment]
@mrthlinh 
Got it.
Thanks a lot.
