### ISSUE TITLE
Great project. I'd like to see the latest update

### ISSUE THREAD

**Issue by mainxx** [mrthlinh/FIFA-World-Cup-Prediction#5]
有可能看到明天八强的结果吗？
Is it possible to see the result of the top eight tomorrow?

**Comment by mrthlinh** [comment]
@mainxx I will update the results soon

**Comment by mrthlinh** [comment]
@mainxx I post the lastest prediction, good luck

**Comment by mainxx** [comment]
@mrthlinh The prediction results are very helpful to me. I wonder if it can be updated continuously.
