### ISSUE TITLE
Wrong home_team information?

### ISSUE THREAD

**Issue by hungvancap** [mrthlinh/FIFA-World-Cup-Prediction#7]
Hi,

I noticed that the home _team column in files data_ex1 to 3 has incorrect information. Your features list however doesn't contain that column. Do you have any correct home_team data as that would help increase accuracy?

Also, why the data in the data_ex1 file stopped in 2015 instead of 2018?

And finally, do you have any updates on this project?

Thank you very much.

**Comment by mrthlinh** [comment]
Thanks for your interest to my project. By "incorrect" you mean name of home_team is wrong and is it incorrect for some or all records? After finishing this project and gaining more experience in Data Science and Engineer, I would say prediction of soccer match is very challenging and if you really want to build a complete solution, it would require a complete data pipeline and automation and collect more features like form of each player, injury info, transfer info. Let me know if you have other questions

**Comment by hungvancap** [comment]
Hi,

By "incorrect" I mean its value is incorrect for almost every record, you can take a look at those CSV files to know what I mean (for instance, the 2014 WC is held in Brazil but the home_team value for those rows is just random).
Also, it looks like some of the matches(rows) are missing from the data_ex1 and data_ex2 files.

I am new to Data Science and still learning, I think am better off redoing your project than enhancing it. But still, thanks for your suggestion.

I will let you know when I have other questions.

Thank you.

**Comment by mrthlinh** [comment]
Just put my thought here so if you continue with this project you can have a better start
1. List out all possible features you can retrieve, which feature you can implement an automation - this is important if you want your ML model improves overtime?
2. Perform quick EDA on those features so confirm your hypothesis (is that feature useful?)
3. Tried out different models, in this type of data tree-based model tends to perform better.
